Add Metrics to GenericComponent in Model
verrazzano/verrazzano-crd-generator pull request #14
Opened 2020-10-20 17:13 UTC by ddrechse

2020-10-21 12:49 UTC, mgianatagh commented
This change should have resulted in an update to the generated CRD file for verrazzano model.

2020-10-22 18:32 UTC, markxnelson approved these changes

2020-10-22 18:35 UTC, bobdonat commented
Yes, there should be a new CRD as part of this PR.  Must do a `make go-build`.

2020-10-22 18:36 UTC, bobdonat requested changes
Please do `make go-build` to create a new model  crd yaml file

2020-10-22 18:51 UTC, bobdonat approved these changes

2020-10-22 18:51 UTC, mgianatagh approved these changes

2020-10-22 18:59 UTC, merged